import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import WagmiProviderWrapper from "./components/WagmiProviderWrapper";
import { AuthProvider } from "./context/authContext";
import { headers } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = headers().get("cookie");

  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <WagmiProviderWrapper cookie={cookie}>{children}</WagmiProviderWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
